#server:
#  port: 2001
#spring:
#  application:
#    name: eureka-demo
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  instance:
#    hostname: localhost
